buildVariable: true
category:
- SERIF
familyName: Noto Nastaliq Urdu
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoNastaliqUrdu.glyphspackage
